###################
### MY PROGRAMS ###
###################

$terminal = foot
$menu = hyprlauncher
$browser = zen # Using the flatpak wrapper in ~/.local/bin
$editor = code # Launched with gnome-keyring store using the argv.json file accessible by "Preferences: Configure Runtime Arguments" command

##############
### SOURCE ###
##############

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
