input {
    kb_layout = it
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =

    follow_mouse = 1
    sensitivity = 0
	  accel_profile = adaptive

    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }
}

gesture = 3, horizontal, workspace
