monitorv2 {
    output     = DP-1
    mode       = 2880x1800@120
    position   = 0x0
    scale      = 1
    vrr        = 1    
    bitdepth   = 10
    cm         = hdr   
}

render {
    direct_scanout    = 1
    cm_fs_passthrough = 1
}

xwayland {
  force_zero_scaling = true
}
