monitorv2 {
    output     = DP-1
    mode       = 2880x1800@120
    position   = 0x0
    scale      = 1
    vrr        = 1      # 0=off, 1=always, 2=fullscreen only, 3=fullscreen+osd
    bitdepth   = 10
    cm         = hdr    # wide color gamut + HDR PQ transfer function
}

render {
    direct_scanout    = 1
    cm_fs_passthrough = 1   # passa in HDR nativo per app fullscreen
}
