windowrule = float on, match:modal 1
windowrule = float on, match:title .*Dialog.*
windowrule = float on, match:title .*Open.*
windowrule = float on, match:title .*Save.*


# Zed
windowrule = workspace 1, match:class ^dev\.zed\.Zed$

# VSCode
windowrule = workspace 1, match:class ^code$
windowrule = fullscreen on, match:class ^code$, match:modal 0, match:title negative:.*(Dialog|Open|Save).*

# Zen
windowrule = workspace 2, match:class ^app\.zen_browser\.zen$
windowrule = fullscreen on, match:class ^app\.zen_browser\.zen$, match:modal 0, match:title negative:.*(Dialog|Open|Save).*

# Kitty
windowrule = workspace 3, match:class ^kitty$
